# Generated by Django 5.1.4 on 2025-04-21 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_manager', '0002_showing_schedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['name']},
        ),
    ]
