# Generated by Django 5.1.4 on 2025-04-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_manager', '0004_alter_movie_last_watched_showing_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
