# Generated by Django 5.1.4 on 2025-04-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_manager', '0005_showing_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showing',
            name='slug',
        ),
        migrations.AddField(
            model_name='schedule',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
