# Generated by Django 5.1.4 on 2025-04-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_manager', '0006_remove_showing_slug_schedule_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='critic_score',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
