# Generated by Django 5.1.4 on 2025-04-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_manager', '0008_rename_critic_score_movie_critic_scores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='showings',
            field=models.ManyToManyField(blank=True, null=True, to='movie_manager.showing'),
        ),
    ]
