# Generated by Django 5.1.4 on 2025-04-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_manager', '0009_alter_schedule_showings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='showings',
            field=models.ManyToManyField(blank=True, to='movie_manager.showing'),
        ),
    ]
