# Generated by Django 5.1.4 on 2025-04-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_manager', '0010_alter_schedule_showings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='mpaa_rating',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
